### PR TITLE
Update to work with the new wallabag api (current v2)

### PR DESCRIPTION
**Pull request by 0wnrepo**
- get the correct feed url
- minor updates to the settings page to reflect the user name instead of user id

### CODE REVIEW

**Comment by 0wnrepo** [comment]
I'll take a look tomorrow to see why it failed.

**Comment by nicosomb** [comment]
This app is not dead! Thank you ;-)

**Comment by 0wnrepo** [comment]
Well, I'm going to take a look around to see what can be improved.

**Comment by 0wnrepo** [comment]
Question here, didn't test with wallabag v1. Does it still work with that (before my changes) ?
If so, I'll add a checkbox to select which version.

**Comment by nicosomb** [comment]
How can iPhone users test this version?

**Comment by 0wnrepo** [comment]
Do we have access to the travis build binary ? We can integrate that with testfairy (I don't currently own an apple developer certificate that I can share), but testfairy is a platform where you send your build and it notifies the testers via email and they can download and run that on their phones. (we can also do this for android)

Documentation for testfairy : http://docs.testfairy.com/
Main Website : http://testfairy.com

I've been using it since inception, works great. Crash reports + lots of debugging features.

**Comment by 0wnrepo** [comment]
Request for comments.

**Comment by j0k3r** [comment]
I can try to test it when I'll have some time.
What do I have to check to see if every thing is ok ?

**Comment by nicosomb** [comment]
Hello @0wnrepo! 

Can you tell us how can we test? You can have testers ;-) https://twitter.com/timscha/status/719793914367094784

**Comment by timscha** [comment]
:) I can test it on an iPhone and iPad Pro. Just let me know how the things work. :)

**Comment by khinsen** [comment]
@0wnrepo I am trying to follow your instructions for building and testing on my iPad. But even with everything set to "Don't code sign", I can't build the ShareExtension 

 | Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.

When I ask XCode to resolve that issue, I get:

 | An App ID with Identifier 'de.Kevin-Meyer.Wallabag.ShareExtension' is not available.
 | Please enter a different string.

I changed the ID to something else, leading to

 | Your account does not have sufficient permissions to modify containers.

Note that I only have the minimal (free) level of developer account. Could that be insufficient?

**Comment by 0wnrepo** [comment]
Hi guys, I only have time for this next week.

**Comment by bohdan-s** [comment]
Anyone got this to build? I am trying to build, I have run the following commands:
```
git clone https://github.com/wallabag/ios-app.git Wallabag
cd Wallabag
git fetch origin pull/32/head:pr-32
git checkout pr-32
pod install
```
And I am getting the following error:

> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_WALAppDelegate", referenced from:
>       objc-class-ref in main.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bohdan-s** [comment]
OK, finally got it to build, looks like the Feed URL has not been updated, the requests look like this:
`%BASEURL%/%ClientID%/%ClientSecret%/unread.xml`
Documentation says it should look like this:
```
http POST http://v2.wallabag.org/oauth/v2/token \
    grant_type=password \
    client_id=12_5um6nz50ceg4088c0840wwc0kgg44g00kk84og044ggkscso0k \
    client_secret=3qd12zpeaxes8cwg8c0404g888co4wo8kc4gcw0occww8cgw4k \
    username=yourUsername \
    password=yourPassw0rd
```

**Comment by tcitworld** [comment]
You're mistaking the rss feeds that were used before and the new api calls.

**Comment by bohdan-s** [comment]
Ahh, thank you.
OK tested again using RSS settings, and the App logs in and pull the reed ok.
Can not add articles using the "Add Article" menu option or the Safari Extension. 404 not found error.

**Comment by deruli79** [comment]
Hi everyone, I did some tests and was able to retrieve articles, but "Adding Articles" still does not work. Any chance to get this working. I am willing to do further testing.
Thanks

**Comment by nicosomb** [comment]
FYI https://twitter.com/bourvill/status/798231305888534528

**Comment by brabalan** [comment]
The application launches with no issue. What server should I use for testing (if I understand, framabag is not ready yet)?

**Comment by nicosomb** [comment]
@brabalan you can create an account on http://v2.wallabag.org (demo platform)

**Comment by brabalan** [comment]
I was able to create an account, but I'm having problems after that. Where should we report bugs, in this issue?

- where do we get a client id & secret? I created a new one, but do I need to?
- I cannot login (I get a login error) with my username and password from the app. The same works from the web.

**Comment by j0k3r** [comment]
Issue should be reported here: https://github.com/wallabag/ios-app
This repo is no longer maintain.

**Pull request closed without merging**
